### ISSUE TITLE
[bug] The website is 404

### ISSUE THREAD

**Issue by ramsayleung** [deb-sig/double-entry-generator#102]
## Describe the bug

挂在项目右侧的链接: [deb-sig.github.io/deg-online/](https://deb-sig.github.io/deg-online/) 404了

## To Reproduce

1. 打开 Repository: https://github.com/deb-sig/double-entry-generator
2. 点击右侧链接: [deb-sig.github.io/deg-online/](https://deb-sig.github.io/deg-online/)
3. 404: There isn't a GitHub Pages site here.

## Expected behavior
1. 指向正确的网站链接
2. 或者：如果还没有官网页面的话，可以指向项目本身 https://github.com/deb-sig/double-entry-generator

**Comment by Triple-Z** [comment]
本来是指向一个 wasm 项目的，后来 wasm 部署地址改成这个了 https://deg-online.pages.dev/ 。

不过这个项目目前有点问题，可以先改回 repo 地址。
