### ISSUE TITLE
Nix Package Support

### ISSUE THREAD

**Issue by A1ca7raz** [deb-sig/double-entry-generator#117]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add packages to flake outputs.

**Describe alternatives you've considered**

**Additional context**

**Comment by Triple-Z** [comment]
PR is welcome~

**Comment by rennsax** [comment]
Done with https://github.com/NixOS/nixpkgs/pull/347402.

**Comment by Triple-Z** [comment]
@rennsax Thx for your contribution ❤️
