### ISSUE TITLE
v2.5.0 版本的可执行文件如何下载？

### ISSUE THREAD

**Issue by frankwuzp** [deb-sig/double-entry-generator#120]
请教大佬，v2.5.0 版本的可执行文件如何建构/下载，目前通过 Homebrew 只能安装到 v2.1.0，微信账单的功能受限，求助……是否有可直接执行的二进制文件，或者建构的方法？谢谢！

**Comment by Triple-Z** [comment]
Sorry for the inconvenience, you can get builds from [v2.5.0 Release Page](https://github.com/deb-sig/double-entry-generator/releases/tag/v2.5.0) .

**Comment by Triple-Z** [comment]
Homebrew fixed at https://github.com/deb-sig/homebrew-tap/commit/50f8d4e3051deadd7104daa0e4de84ab5c34f16c
