### ISSUE TITLE
feat: add metadata for beancount postings

### ISSUE THREAD

**Issue by Triple-Z** [deb-sig/double-entry-generator#21]
Add [metadata](https://beancount.github.io/docs/beancount_language_syntax.html#metadata-1) for generated beancount postings, like the following example.

```diff
- 2021-05-20 * "苏宁易购官方旗舰店" "【礼遇价】三星128g内存卡microSD存储卡tf卡行车记录仪卡switch监控摄像头"  ; 支出-交易成功-数码电器
+ 2021-05-20 * "苏宁易购官方旗舰店" "【礼遇价】三星128g内存卡microSD存储卡tf卡行车记录仪卡switch监控摄像头"
	Expenses:Electronics 87.90 CNY
	Assets:Bank:CN:CMB-9876:Savings -87.90 CNY
+       source: "支付宝"
+       payTime: "2021-05-20 12:34"
+       category: "数码电器"
+       status: "交易成功"
+       txStatus: "支出"
+       note: "支出-交易成功-数码电器"
```

We can also move the comment `Note` to metadata.

**Comment by gaocegege** [comment]
SGTM

**Comment by Triple-Z** [comment]
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/16285716/123298002-a9eb5300-d54a-11eb-8ae5-02ac06e40842.png">

The transaction's metadata are shown on Fava.

Schedule this feature to `v1.1.0`?

/cc @gaocegege

**Comment by gaocegege** [comment]
SGTM
