### ISSUE TITLE
wechat: Failed to get the tx type 购买理财通 和 零钱通转出-到零钱

### ISSUE THREAD

**Issue by milkyfox** [deb-sig/double-entry-generator#29]
还有一种小韭菜的交易类型也会报错

```
 Failed to translate: Failed to translate bill: line 149: Failed to get the tx type 购买理财通: <nil>
```
这是账单数据
```
2020-02-14 01:32:14,购买理财通,理财通,"鹏华增值宝(000569)",/,¥10000.00,浦发银行,支付成功,1800007367312002141165262215	,1800007308102002143430655989	,"/"
2020-02-14 01:24:33,购买理财通,理财通,"中欧医疗健康混合C(003096)",/,¥3000.00,浦发银行,支付成功,1800045030312002144223548046	,1800007030102002143310679508	,"/"
```

**Comment by milkyfox** [comment]
这里有零钱通转出到零钱的报错

```
Failed to translate: Failed to translate bill: line 152: Failed to get the tx type 零钱通转出-到零钱
```

这是账单数据

```
2020-02-14 01:19:39,零钱通转出-到零钱,/,"/",/,¥2634.78,零钱通,支付成功,18000070012002140012244807617587	,/	,"/"

```

**Comment by Triple-Z** [comment]
> 还有一种小韭菜的交易类型也会报错
> 
> ```
>  Failed to translate: Failed to translate bill: line 149: Failed to get the tx type 购买理财通: <nil>
> ```
> 
> 这是账单数据
> 
> ```
> 2020-02-14 01:32:14,购买理财通,理财通,"鹏华增值宝(000569)",/,¥10000.00,浦发银行,支付成功,1800007367312002141165262215	,1800007308102002143430655989	,"/"
> 2020-02-14 01:24:33,购买理财通,理财通,"中欧医疗健康混合C(003096)",/,¥3000.00,浦发银行,支付成功,1800045030312002144223548046	,1800007030102002143310679508	,"/"
> ```

那有没有「卖出理财通」的类型 。。。

**Comment by milkyfox** [comment]
> > 还有一种小韭菜的交易类型也会报错
> > ```
> >  Failed to translate: Failed to translate bill: line 149: Failed to get the tx type 购买理财通: <nil>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这是账单数据
> > ```
> > 2020-02-14 01:32:14,购买理财通,理财通,"鹏华增值宝(000569)",/,¥10000.00,浦发银行,支付成功,1800007367312002141165262215	,1800007308102002143430655989	,"/"
> > 2020-02-14 01:24:33,购买理财通,理财通,"中欧医疗健康混合C(003096)",/,¥3000.00,浦发银行,支付成功,1800045030312002144223548046	,1800007030102002143310679508	,"/"
> > ```
> 
> 那有没有「卖出理财通」的类型 。。。

我试了一下，理财通的钱转出到银行卡是不会记录在账单里面的。转出到零钱我刚用零钱买了一笔，预计后天就可以卖出看结果了。

- - -

这里还有几个报错

```
2019-04-16 10:28:55,零钱充值,建设银行(7867),"/",/,¥1300.00,建设银行(7867),充值完成,110190416100031243293946287587	,/	,"/"
2019-02-02 14:11:29,零钱充值,建设银行(7867),"/",/,¥0.01,建设银行(7867),充值完成,110190202100031243058544748587	,/	,"/"

```

**Comment by Triple-Z** [comment]
> 我试了一下，理财通的钱转出到银行卡是不会记录在账单里面的。

那这样很容易产生对账问题呀，到时候需要手动看银行卡账单才能发现这笔帐。

**Comment by milkyfox** [comment]
> > 我试了一下，理财通的钱转出到银行卡是不会记录在账单里面的。
> 
> 那这样很容易产生对账问题呀，到时候需要手动看银行卡账单才能发现这笔帐。

是的。

理财通转出到银行卡、零钱通、零钱都不会记录在账单里面，只能手动处理了。

**Comment by Triple-Z** [comment]
Closed for #30 is merged.
