### ISSUE TITLE
wechat: Failed to get the tx type 亲属卡交易

### ISSUE THREAD

**Issue by wodi621** [deb-sig/double-entry-generator#33]
发现一个类型好像没有被支持。
“亲属卡交易”这个类型提示：Failed to translate: Failed to translate bill: line 43: Failed to get the tx type 亲属卡交易: <nil>
，会报错停止

目前是手动修改类型暂时解决。

亲属卡交易
>2021-10-19 16:08:00,亲属卡交易,哈哈,"亲属卡",支出,¥2243.46,零钱通,支付成功,42000011202110191201583411	,XSFF-SD2021101916055813620	,"/"

**Comment by gaocegege** [comment]
Thanks for the issue!

**Comment by gaocegege** [comment]
Can you please give us a sample to reproduce it?

I do not open such a card thus I cannot test it.

**Comment by Triple-Z** [comment]
> Can you please give us a sample to reproduce it?

This is the example (in his comment quote):

```csv
2021-10-19 16:08:00,亲属卡交易,哈哈,"亲属卡",支出,¥2243.46,零钱通,支付成功,42000011202110191201583411 ,XSFF-SD2021101916055813620 ,"/"
```
