### ISSUE TITLE
支付宝似乎更新了帐单格式

### ISSUE THREAD

**Issue by ppodxiang** [deb-sig/double-entry-generator#35]
2021-12-12测试导出的支付宝账单
.csv文件里，交易时间隐去了秒，对方账号多了双引号等
目前alipay导入工具暂不适配

**Comment by gaocegege** [comment]
Thanks for the issue! We will have a look ASAP.

**Comment by Triple-Z** [comment]
/ack @gaocegege 

I will investigate this tonight.

**Comment by ppodxiang** [comment]
抱歉 似乎是在打开支付宝导出的csv时，产生了上述变化，实测直接转换原csv文件是正常的，乌龙了。

**Comment by gaocegege** [comment]
No worry :-)

**Comment by qninth** [comment]
不要用Excel等工具重新保存csv文件，否则会发生错误~
