### ISSUE TITLE
[feat] Support version command when releasing or go get 

### ISSUE THREAD

**Issue by gaocegege** [deb-sig/double-entry-generator#45]
Now there is no version here

2022/01/05 14:26:33 double-entry-generator Version: UNKNOWN, Commit: UNKNOWN, Build Path: UNKNOWN

**Comment by Triple-Z** [comment]
It seems that the version info only exists when using the `make build`:

https://github.com/deb-sig/double-entry-generator/blob/25538b692ec954edeeca8202054b1003c2c0909f/Makefile#L33-L35

However, the `goreleaser` uses `go build` command to build the binaries, so the released binaries don't have the version info.

**Comment by Triple-Z** [comment]
<img width="850" alt="image" src="https://user-images.githubusercontent.com/16285716/154504432-fef46954-bd9c-42d1-b038-70ac10c65ab7.png">

It works!
