### ISSUE TITLE
Is it more appropriate to use full match than partial match in some positions?

### ISSUE THREAD

**Issue by z2z23n0** [deb-sig/double-entry-generator#49]
Using partial matches in some items of the config file may cause problems.

For example, when I make the following settings:
```yaml
method: 余额
methodAccount: Assets:Alipay:Balance
```
It will also match this record, which means you use two payment accounts:
```yaml
...
method: "招商银行储蓄卡(8888)&余额"
...
```
This will result in only one payment account being generated and will not be marked with FIXME, so you may have difficulty finding errors.

So should we consider using full matches instead of partial matches in some items?

**Comment by Triple-Z** [comment]
SGTM

**Comment by z2z23n0** [comment]
I would like to make a PR about this if you guys are busy.
@Triple-Z @gaocegege

**Comment by Triple-Z** [comment]
@z2z23n0 That will be great! Look forward to your PR~
