### ISSUE TITLE
支付宝账单更新了新格式

### ISSUE THREAD

**Issue by wchen9** [deb-sig/double-entry-generator#84]
不知道我是被灰度了还是所有人都是这样，示例如下：

```
------------------------------------------------------------------------------------
导出信息：
姓名：xx
支付宝账户：xx@gmail.com
起始时间：[2023-02-10 00:00:00]    终止时间：[2023-02-13 23:59:59]
导出交易类型：[全部]
导出时间：[2023-02-13 09:12:52]
共66笔记录
收入：1笔 28.50元
支出：63笔 16.54元
不计收支：2笔 16.37元

特别提示：
1.本回单内容可表明支付宝受理了相应支付交易申请，因系统原因或通讯故障等偶发因素导致本回单与实际交易结果不符时，以实际交易情况为准；
2.请勿将本回单作为收款方发货的凭据使用，请查证账户实际到账情况后再进行发货操作；
3.支付宝快捷支付等非余额支付方式可能既产生支付宝交易也同步产生银行交易，因此请勿使用本回单进行重复记账；
4.本回单如经任何涂改、编造，均立即失去效力；
5.部分账单如：充值提现、账户转存或者个人设置收支等不计入为收入或者支出，记为不计收支类；
6.因统计逻辑不同，明细金额直接累加后，可能会和下方统计金额不一致，请以实际交易金额为准；
7.禁止将本回单用于非法用途；
8.本明细仅展示当前账单中的交易，不包括已删除的记录；
9.本明细仅供个人对账使用。

------------------------支付宝（中国）网络技术有限公司  电子客户回单------------------------
交易时间            ,交易分类                ,交易对方                ,对方账号                ,商品说明                ,收/支                 ,金额                  ,收/付款方式              ,交易状态                ,交易订单号     ,商家订单号           ,备注                  ,
2023-02-12 21:32:14 ,亲友代付                ,xxxxxxxxxxxx          ,/                   ,亲情卡                 ,支出                  ,49.74               ,交通银行信用卡(7449)       ,交易成功                ,202302xxxxxx0011000103xxxxxx	,20230xxxxxxx014741014xxxxxx	,                    ,

```

**Comment by eiav66** [comment]
另外新的Alipay账单的交易时间已经隐去了秒钟。

**Comment by sharp-tasting** [comment]
I have encountered this problem too.

**Comment by Triple-Z** [comment]
看起来是原来 csv 文件中的结尾部分放到前面去了。

**Comment by sharp-tasting** [comment]
> 看起来是原来 csv 文件中的结尾部分放到前面去了。

I tried to edit the csv to make it the same old style (cut the head and paste to the end), and then double-entry-generate it. 
But this didn't change the result, which is an empty transaction list...
Because the _order of columns_ is also changed. 

The old column order is 

> ------------------------支付宝（中国）网络技术有限公司  电子客户回单------------------------
> 收/支                 ,交易对方                ,对方账号                ,商品说明                ,收/付款方式              ,金额                  ,交易状态                ,交易分类                ,交易订单号     ,商家订单号           ,交易时间            ,
> 收入                  ,某公司        ,                    ,某商品              ,                    ,0.03                ,交易成功                ,转账红包                ,20211231234	,1234	,2021-12-31 08:28:29 ,
> 

while the new column order is 

> ------------------------支付宝（中国）网络技术有限公司  电子客户回单------------------------
> 交易时间            ,交易分类                ,交易对方                ,对方账号                ,商品说明                ,收/支                 ,金额                  ,收/付款方式              ,交易状态                ,交易订单号     ,商家订单号           ,备注                  ,
> 2023-02-17 12:34:56 ,餐饮美食                ,1234餐厅             ,/                   ,北京-1234号             ,支出                  ,24.00               ,中国银行信用卡(1234)     ,交易成功                ,202302171234	,1234	,                    ,

**Comment by Triple-Z** [comment]
> Because the _order of columns_ is also changed.

Look like the code MUST be changed for Alipay's new format.

**Comment by xiaoyuesansui** [comment]
Same problem here 
遇到了同样的问题

**Comment by skymagician** [comment]
+1

**Comment by gaocegege** [comment]
@Triple-Z 我们可以发一个新版本么？

**Comment by Triple-Z** [comment]
> @Triple-Z 我们可以发一个新版本么？

好，发一个版本。

**Comment by Triple-Z** [comment]
该功能修复已经包含在 [v2.0.0 版本](https://github.com/deb-sig/double-entry-generator/releases/tag/v2.0.0) 中。

**Comment by skymagician** [comment]
> > @Triple-Z 我们可以发一个新版本么？
> 
> 好，发一个版本。

希望同步homebrew，我是用brew安装的。

**Comment by Triple-Z** [comment]
> 希望同步homebrew，我是用brew安装的。

Homebrew 也已经发布： https://github.com/deb-sig/homebrew-tap/commit/54ac40b3eea295c63000f2c12b2607b8f38fcee4
