### ISSUE TITLE
feat[ledger]: add support for `ledger-cli`

### ISSUE THREAD

**Issue by ramsayleung** [deb-sig/double-entry-generator#92]
Hi, Thanks for your great work on this project.

## Context 
我也在用复式记账，但是使用的是 `ledger`  而非 `beancount`. 

## Feature Request
目前 `double-entry-generator` 尚且只支持 `beancount`, 而 `beancount` 和 `ledger` 的记账语法类似，所以我希望 `double-entry-generator` 也可以支持 `ledger`.

## TODO List

目前我已经给 `double-entry-generator` 增加了 `ledger` 的支持，代码部分已经写完并且自测可行。
但只实现对部分 provider 的支持:
- [x] `普通消费账单`的模板
- [x] `火币模板1` 
- [x]  `火币模板2`
- [x]  `火币卖出模板`
- [x]  `海通买入模板`
- [x]  `海通卖出模板`

## Action

在发起 PR 之前，我想先在 issue 分享一下这个 **增加对 `ledger` 支持的feature** 的想法. 

如果能达成共识的话，我倾向将功能拆分成多个PR, 以避免单个 PR 过大，导致不易 Review.

**Comment by Triple-Z** [comment]
SGTM👍 PRs are welcome. 

@gaocegege IR has multiple backends finally🤣

**Comment by Triple-Z** [comment]
忘记改 README 了 🤣 

<img width="976" alt="image" src="https://github.com/deb-sig/double-entry-generator/assets/16285716/ff64c3f4-7f73-433f-9438-a882d2bf28b7">

**Comment by ramsayleung** [comment]
这个本来就打算先不改的，等把所有的模板支持都加上之后再修改的。

现在修改了，用户使用时就会发现， ledger 后端还不支持 `huobi` 和 `htsec`.

功能完备之后再开启流量灰度 :)

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

**Comment by Triple-Z** [comment]
貌似只剩下修改文档了。

**Comment by ramsayleung** [comment]
PR 在路上了 :)
