### ISSUE TITLE
[feat] discuss the useless fields

### ISSUE THREAD

**Issue by ramsayleung** [deb-sig/double-entry-generator#97]
## Is your feature request related to a problem? Please describe.

我发现[ `compiler/beancount/template` ](https://github.com/deb-sig/double-entry-generator/blob/master/pkg/compiler/beancount/template.go#L124) 里面, `htsec` 卖出和买入模板的三个字段是被定义与赋值了，但是未在模板中使用的.

```go
type HtsecTradeBuyOrderVars struct {
	PayTime           time.Time
	Peer              string
	TxTypeOriginal    string
	TypeOriginal      string
	Item              string
	CashAccount       string
	PositionAccount   string
	CommissionAccount string
	PnlAccount        string
	Amount            float64
	Money             float64
	Commission        float64
	Price             float64
	BaseUnit          string // 未使用
	TargetUnit        string // 未使用
	CommissionUnit    string // 未使用
	Currency          string
}
```

## Describe the solution you'd like

删除掉`htsec`模板中的 `BaseUnit`, `TargetUnit`, `CommissionUnit` 无用字段.

**Comment by Triple-Z** [comment]
Thanks for your contribution!
